/**
 * Debt-recovery content guard.
 *
 * AdminOS auto-sends only tiers 1–3 (courteous factual reminders) and drafts
 * anything harsher for the owner to send themselves. The auto-send text for
 * tiers 1–3 is generated by an LLM under a tightly-constrained prompt that
 * forbids any threat or legal reference. This guard is the belt to that prompt's
 * braces: a message that trips it is NOT sent as free-form, so a model that
 * ignores its instructions cannot put a false legal threat on the wire.
 *
 * Why this matters beyond politeness: a business dunning its own customer with
 * fabricated legal threats — "a letter of demand has been issued", "legal
 * proceedings begin in N days" — is the Debt Collectors Act fact pattern, and
 * AdminOS sends from its own infrastructure on the tenant's behalf. The guard is
 * a legal control, not a tone preference.
 *
 * LIMITATION: the deny-list is English-first with a few common Afrikaans/isiZulu
 * terms. It is defence-in-depth, NOT the primary control — the constrained
 * prompt is. Reminders generate in the tenant's language, so a threat phrased in
 * an unlisted language could pass the guard; that is why a tripped guard falls
 * back to a vetted, human-written template rather than to "send anyway". When a
 * proper multilingual moderation pass exists, widen this.
 */

// Word-bounded terms: matched case-insensitively on word boundaries so "sue"
// does not fire on "issue" or "pursue", and "court" does not fire on "courteous".
// Works for English and Afrikaans, whose words are not heavily prefixed.
const FORBIDDEN_TERMS: string[] = [
  // English — legal process & enforcement
  'legal', 'lawyer', 'attorney', 'court', 'summons', 'subpoena',
  'letter of demand', 'demand letter', 'litigation', 'litigate', 'sue', 'sued', 'lawsuit',
  'prosecute', 'prosecution', 'judgment', 'judgement', 'sheriff', 'garnish', 'garnishee',
  'debt collector', 'collections agency', 'collection agency',
  'blacklist', 'blacklisted', 'credit bureau', 'credit record', 'creditworthiness',
  'seize', 'repossess', 'repossession', 'warrant',
  // Afrikaans — common equivalents
  'prokureur', 'hof', 'dagvaarding', 'skuldinvorderaar',
]

// Agglutinative stems: isiZulu/isiXhosa (and some Afrikaans) attach prefixes to
// the noun — "court" is inkantolo but appears as enkantolo, ezinkantolo, etc.
// Word boundaries would miss those, so these match as substrings. Each stem is
// chosen to be distinctive enough not to collide with a common word: e.g. the
// isiXhosa "icala" (case) is deliberately NOT here — its stem "cala" also sits
// inside "escalate". Better to miss it and defer than to false-positive.
const FORBIDDEN_STEMS: string[] = [
  'nkantolo',  // isiZulu/isiXhosa: court  (i-/e-/ezin- nkantolo)
  'mmeli',     // isiZulu/isiXhosa: lawyer (u-/aba- mmeli)
  'regstap',   // Afrikaans: legal step(s) (regstap / regstappe)
]

const FORBIDDEN_WORD_PATTERN = new RegExp(
  `\\b(${FORBIDDEN_TERMS.map(escapeRegExp).join('|')})\\b`,
  'iu',
)

const FORBIDDEN_STEM_PATTERN = new RegExp(
  `(${FORBIDDEN_STEMS.map(escapeRegExp).join('|')})`,
  'iu',
)

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export interface GuardResult {
  safe: boolean
  /** The forbidden term that tripped the guard, for the audit log. Empty when safe. */
  matched: string
}

/**
 * Returns whether an automated reminder is safe to send as free-form text.
 * A non-empty, non-whitespace message with no forbidden term is safe.
 */
export function checkRecoveryMessage(message: string): GuardResult {
  if (!message || !message.trim()) {
    return { safe: false, matched: '(empty)' }
  }
  const word = FORBIDDEN_WORD_PATTERN.exec(message)
  if (word) return { safe: false, matched: word[0].toLowerCase() }

  const stem = FORBIDDEN_STEM_PATTERN.exec(message)
  if (stem) return { safe: false, matched: stem[0].toLowerCase() }

  return { safe: true, matched: '' }
}
