import { formatZAR } from '@/lib/format'
import { escHtml, DOC_PRINT_CSS } from '@/lib/documents/htmlDoc'

export interface ReceiptDocData {
  receiptNumber: string
  invoiceNumber: string
  paidDate: string
  companyName: string
  companyAddress: string | null
  companyVatNumber: string | null
  logoUrl: string | null
  paidByName: string
  amountPaid: number
  isPartial: boolean
}

export function generateReceiptHTML(data: ReceiptDocData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Receipt ${escHtml(data.receiptNumber)} — ${escHtml(data.companyName)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #111; background: #fff; padding: 24px; }
  .doc { max-width: 700px; margin: 0 auto; border: 1px solid #ccc; padding: 24px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; border-bottom: 2px solid #166534; padding-bottom: 16px; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand img { max-height: 48px; max-width: 160px; object-fit: contain; }
  .company-name { font-size: 18px; font-weight: bold; color: #166534; }
  .company-details { font-size: 10px; color: #555; margin-top: 4px; }
  .doc-title { text-align: right; }
  .doc-title h1 { font-size: 16px; font-weight: bold; color: #166534; letter-spacing: 0.5px; }
  .doc-title .meta { font-size: 11px; color: #555; margin-top: 4px; }
  .confirm-box { text-align: center; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 24px; margin: 20px 0; }
  .confirm-box .label { font-size: 10px; text-transform: uppercase; color: #166534; margin-bottom: 6px; }
  .confirm-box .amount { font-size: 26px; font-weight: bold; color: #166534; }
  .details { background: #f8fafc; padding: 12px; border-radius: 4px; font-size: 11px; }
  .details .row { display: flex; justify-content: space-between; padding: 4px 0; }
  .details .row + .row { border-top: 1px solid #eee; }
  .generated-note { text-align: center; margin-top: 16px; font-size: 9px; color: #aaa; }
  ${DOC_PRINT_CSS}
</style>
</head>
<body>
<div class="doc">

  <div class="header">
    <div class="brand">
      ${data.logoUrl ? `<img src="${escHtml(data.logoUrl)}" alt="${escHtml(data.companyName)} logo">` : ''}
      <div>
        <div class="company-name">${escHtml(data.companyName)}</div>
        ${data.companyAddress ? `<div class="company-details">${escHtml(data.companyAddress)}</div>` : ''}
        ${data.companyVatNumber ? `<div class="company-details">VAT No: ${escHtml(data.companyVatNumber)}</div>` : ''}
      </div>
    </div>
    <div class="doc-title">
      <h1>PAYMENT RECEIPT</h1>
      <div class="meta">${escHtml(data.receiptNumber)}</div>
      <div class="meta">${escHtml(data.paidDate)}</div>
    </div>
  </div>

  <div class="confirm-box">
    <div class="label">${data.isPartial ? 'Partial payment received' : 'Payment received in full'}</div>
    <div class="amount">${formatZAR(data.amountPaid, { cents: true })}</div>
  </div>

  <div class="details">
    <div class="row"><span>Received from</span><strong>${escHtml(data.paidByName)}</strong></div>
    <div class="row"><span>For invoice</span><strong>${escHtml(data.invoiceNumber)}</strong></div>
    <div class="row"><span>Date</span><strong>${escHtml(data.paidDate)}</strong></div>
  </div>

  <div class="generated-note">Generated by AdminOS — ${escHtml(data.companyName)} | ${new Date().toLocaleDateString('en-ZA')}</div>

</div>
</body>
</html>`
}
